name: KommandTestPlugin
main: com.github.imalwayscoding.plugin.KommandTestPlugin
version: $pluginVersion
api-version: '1.16'
depend: [Kotlin]
author: 'IlyLine_'

commands:
  kt:
    usage: /<command> help
    permission: kommandtest.command
    description: KommandTest command.

permissions:
  kommandtest.command:
    default: op
    description: KommandTest command permission.